## Numpy

In [2]:
## pip install numpy

In [1]:
import numpy as np

In [3]:
### data type
a = np.array([1,2,3,4,5])
print(a.dtype)

int32


In [2]:
### dimension
a = np.array([1,2,3,4,5])
print(a.ndim)

1


In [3]:
a = np.array([[1,2,4,5],[2,3,8,9]])
print(a.ndim)

2


In [4]:
a = np.array([[1,2,4,5],[2,3,8,9]],dtype='float')
print(a.ndim)
print(a)

2
[[1. 2. 4. 5.]
 [2. 3. 8. 9.]]


In [4]:
### making array
z = np.zeros((5,7),dtype=int)
print(z)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [5]:
z = np.ones((5,7))
print(z)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [2]:
z = np.full((5,7),8)
print(z)

[[8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]]


In [8]:
z = np.full((5,7),6,dtype='float')
print(z)

[[6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]]


In [27]:
r = np.arange(1,15,1)
print(r)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
r = np.arange(2,15,2)
print(r)

[ 2  4  6  8 10 12 14]


In [9]:
### indexing
r = np.arange(2,15,2)
print(r)
print(r[2])

[ 2  4  6  8 10 12 14]
6


In [9]:
##reshape
##convert 1d to 2-d
f = np.arange(1,13,1).reshape((2,6))
print(f)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [10]:
f = np.arange(1,13,2).reshape((2,3))
print(f)

[[ 1  3  5]
 [ 7  9 11]]


In [7]:
## 2d-1d
z = np.full((2,3),6,dtype='float').flatten()
print(z)

[6. 6. 6. 6. 6. 6.]


In [11]:
z = np.full((4,5),6,dtype='float').flatten()
print(z)

[6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]


In [14]:
##indeing
a = np.array([[2,3],[4,5]])
print(a[0,1])

3


In [25]:
##slicing
r = np.arange(2,15,2)
print(r)
print(r[1::2])

[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 3  5  7  9 11 13]


In [16]:
##slicing 2-d array
a= np.array([[2,4,7,9],[11,15,2,8]])
print(a[0,1::2])
print(a[1,1::1])



[4 9]
[15  2  8]


In [18]:
## view
a=np.array([[5,3,1],[2,4,6],[8,2,6]])
b = a.view()
a[0,0]= 8
print(a)
print(b)

[[8 3 1]
 [2 4 6]
 [8 2 6]]
[[8 3 1]
 [2 4 6]
 [8 2 6]]


In [19]:
##copy
a=np.array([[5,3,1],[2,4,6],[8,2,6]])
b = a.copy()
a[0,0]= 8
print(a)
print(b)

[[8 3 1]
 [2 4 6]
 [8 2 6]]
[[5 3 1]
 [2 4 6]
 [8 2 6]]


In [20]:
a=np.array([[2,3,4],[9,0,11]])
for i in np.nditer(a):
    print(i)

2
3
4
9
0
11


In [22]:
a=np.array([[2,3,4],[9,0,11]])

for idx,val in np.ndenumerate(a):
    print(idx,val)

(0, 0) 2
(0, 1) 3
(0, 2) 4
(1, 0) 9
(1, 1) 0
(1, 2) 11


In [29]:
### sorting of array
a=np.array([2,14,10,18,2,7,16,9,4])
a = np.sort(a)
print(a)

[ 2  2  4  7  9 10 14 16 18]


In [11]:
### sorting of array
a=np.array([2,14,10,18,2,7,16,9,4])
a = np.sort(a)[::-1]
print(a)


[18 16 14 10  9  7  4  2  2]


In [12]:
x=np.array([[12,11,15],
            [21,25,20],
            [18,27,16]])
x=np.sort(x)
print(x)

[[11 12 15]
 [20 21 25]
 [16 18 27]]


In [14]:
x=np.array([[12,11,15],
            [21,25,20],
            [18,27,16]])

x=np.sort(x,axis=0) ### axis=0- column , axis-1 row
print(x)


[[12 11 15]
 [18 25 16]
 [21 27 20]]


In [30]:
### matrix manipulation

a= np.array([[2,3,4],[9,0,11]])
b= np.array([[5,13,9],[8,10,15]])
print(a+b)

[[ 7 16 13]
 [17 10 26]]


In [31]:
a= np.array([[2,3,4],[9,0,11]])
b= np.array([[5,13,9],[8,10,15]])
print(a-b)

[[ -3 -10  -5]
 [  1 -10  -4]]


In [8]:
a= np.array([[2,3,4],[9,0,11]])
b= np.array([[5,13,9],[8,10,15]])
print(a*b)

[[ 10  39  36]
 [ 72   0 165]]


In [12]:
### matrixx multiplication dot product
a= np.array([[2,3,4],[9,0,11]])
b= np.array([[5,13,9],[8,10,15],[2,8,3]])
print(a.dot(b))

[[ 42  88  75]
 [ 67 205 114]]


In [22]:
### matrixx multiplication dot product  (colunm == row)
a= np.array([[2,3,4],[9,0,11]])
b= np.array([4,5,6])
print(a.dot(b))

[ 47 102]


In [29]:
### inverse
x=np.array([[6,5],[2,1]])
y= np.linalg.inv(x)
print(y)

[[-0.25  1.25]
 [ 0.5  -1.5 ]]


In [30]:
 ### inverse
x=np.array([[1,2,-2],[-1,3,0],[0,-2,1]])
y= np.linalg.inv(x)
print(y)

[[3. 2. 6.]
 [1. 1. 2.]
 [2. 2. 5.]]


In [31]:
## tranpose matrix
a= np.array([[2,3,4],[9,0,11]])
print(np.transpose(a))

[[ 2  9]
 [ 3  0]
 [ 4 11]]


In [3]:
## trace
a= np.array([[2,3,4],[9,0,11]])
print(a)
print(np.trace(a)) # 2+0


[[ 2  3  4]
 [ 9  0 11]]
2


In [4]:
a= np.array([[2,3,4],[9,0,11],[2,6,9]])
print(a)
print(np.trace(a))

[[ 2  3  4]
 [ 9  0 11]
 [ 2  6  9]]
11


In [36]:
##searching - where
a= np.arange(1,50,8)
print(a)
print(np.where(a==41))

[ 1  9 17 25 33 41 49]
(array([5], dtype=int64),)


In [37]:
##searching
a= np.array([41,41,5])
print(a)
print(np.where(a<41))

[41 41  5]
(array([2], dtype=int64),)


In [38]:
a=np.array([1,2,4,5,7,9])
print(np.mean(a))
print(np.average(a))
print(np.median(a))
## mode = 3median - 2mean
print(3*np.median(a)-2*np.mean(a))

4.666666666666667
4.666666666666667
4.5
4.166666666666666


In [39]:
### variance ## standard deviation
a = np.array([1,2,3,4,5])
var = np.var(a)
std = np.std(a)
print(var)
print(std)

2.0
1.4142135623730951
